version: '3'

services:
  node_server:
    container_name: node_server
    image: node:14

    ports:
      - 3000:3000 # web app

    volumes:
      - ./src/:/home/node # mount if src existed

    command: >
          bash -c "cd /home/node && sh init.sh"

  db_maria10:
    container_name: maria10
    hostname: streaming.nexlesoft.com
    image: mariadb:10
    ports:
        - "3307:3306"
    volumes:
        - data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: entrance_test
        MYSQL_USER: test01
        MYSQL_PASSWORD: PlsDoNotShareThePass123@

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
        - 8000:80
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=localhost
        - PMA_PORT=3306

volumes:
    data:
